New amx_debug mode. For use performance monitor without debug mode.
alliedmodders/amxmodx pull request #1028
Opened 2021-12-09 03:55 UTC by UnrealKaraulov

New amx_debug mode 3: Use performance monitor for all plugins.

For use performance monitor without debug mode. **(No performance affect)**

@dvander also this PR can close https://github.com/alliedmodders/amxmodx/pull/1027 as unnecessary.

2021-12-14 04:13 UTC, UnrealKaraulov commented
@dvander you still alive? 👽 

Possible to merge this pr? 
It can add possibly use performance monitoring for plugins in release mode, more accurate than in debug.

2021-12-14 05:01 UTC, dvander commented
Is debug mode required for perf monitor? Eg, should amx_debug be a bitmask, or a level?

2021-12-14 05:54 UTC, UnrealKaraulov commented
> Is debug mode required for perf monitor? Eg, should amx_debug be a bitmask, or a level?
Perf monitor at this time works only for plugins what in debug mode. But this commit add possibly to use it for all plugins, even in release mode.

At this time in master, amx_debug can be 1, and 2.
0 = nothing (as 1)
1 = put in debug only plugins marked 'debug' in plugins.ini
2 = put all plugins in debug (and performance monitor)
3 = nothing (as 1)

This commit add new amx_debug mode '3'
3 = put in debug only plugins marked 'debug' in plugins.ini and force to use performance monitor for all plugins, even if not marked as debug.

2021-12-14 06:00 UTC, dvander commented
It seems like it'd be better to keep amx_debug as-is, and then have a separate flag for the performance monitor.

2021-12-14 06:48 UTC, UnrealKaraulov commented
> It seems like it'd be better to keep amx_debug as-is, and then have a separate flag for the performance monitor.

Something like this : https://github.com/alliedmodders/amxmodx/pull/1028/commits/376cfa0fbeddff25f2cdc0e1d53c320f525bafd0

?????

2021-12-15 04:11 UTC, UnrealKaraulov commented
Updated.
> It seems like it'd be better to keep amx_debug as-is, and then have a separate flag for the performance monitor.

Something like this : https://github.com/alliedmodders/amxmodx/pull/1028/files ??

@dvander Now possible to disable amx_perf, or enable for all plugins. 

0. Disable
1. Enable for debug plugins
2. Enable for all plugins

2021-12-16 11:38 UTC, UnrealKaraulov commented
@dvander now all okay or need another changes?

2022-02-02 16:10 UTC, UnrealKaraulov commented
@dvander This is for previous PR. Now performance monitoring can be Disabled/Enabled for debug plugins/Enabled for anything. You can merge this PR? (because monitor can't be disabled without this fix)

2022-03-03 16:43 UTC, UnrealKaraulov commented
I can compile it in another branch in GitHub actions with artifacts upload. But better if this will be merged. Possible all authors of amxx is dead ;(

2022-03-14 19:00 UTC, UnrealKaraulov commented
@stambeto2006 you can download this version here https://github.com/UnrealKaraulov/amxmodx/actions/runs/1982492726

2022-12-24 10:56 UTC, wopox1337 requested changes

2022-12-24 10:56 UTC, wopox1337 commented on configs/amxx.cfg
> +amx_perfmon_ms 5.0
```suggestion
amx_perfmon_ms 5.0

```

2022-12-24 10:56 UTC, wopox1337 commented on configs/cstrike/amxx.cfg
> +amx_perfmon_ms 5.0
```suggestion
amx_perfmon_ms 5.0

```

2022-12-24 10:56 UTC, wopox1337 commented on configs/ns/amxx.cfg
> +amx_perfmon_ms 5.0
```suggestion
amx_perfmon_ms 5.0

```

2023-01-03 16:11 UTC, rtxa commented
Hi @dvander,

Sorry for tagging you. Would you mind taking a look to this PR? The new *performance monitor* feature is good, but unfortunately it can't be disabled. Seems to me that @UnrealKaraulov made a very simple solution for this issue, where you can disabled it forever, enabled it only for plugins in debug mode or enabled it for all plugins.

Otherwise, it would obsfucated important information for developers not looking for this kind of info, or server owners where plugins are set in debug mode for other type of errors.

A workaround for this issue would be to set `amx_perflog_ms` to some high number like `9999` and it would disable the performance monitor.

2023-09-07 08:44 UTC, UnrealKaraulov commented
@dvander @Arkshine америкосы

2023-09-07 08:44 UTC, closed without merging